# Generated by Django 2.1.2 on 2019-01-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20181022_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Changetime',
            field=models.BooleanField(default=True),
        ),
    ]
